name: Insecure Workflow
on: [push]

jobs:
  insecure_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Expose Secret
        run: |
          echo "SECRET=hardcoded123" >> $GITHUB_ENV

      - name: Dangerous Command
        run: bash -c "$UNTRUSTED_INPUT"